### ISSUE TITLE
Maybe don't write world-readable files?

### ISSUE THREAD

**Issue by twm** [glyph/lancer#4]
I ran lancer on a Gandi domain (which didn't work, but still digging into that). I noticed that the `lancer.json` (minimal concern) and `client.key` (!) files it created are world-readable:

```
$ ll jame.twm.space/certs
total 8.0K
-rwxrwxr-x 1 twm twm 1.7K Jul 15 23:30 client.key*
-rw-rw-r-- 1 twm twm    0 Jul 15 23:25 jame.twm.space.pem
-rwxrwxr-x 1 twm twm   88 Jul 15 23:30 lancer.json*
```

I mean, sure, that's what my umask says to do (it's 002), but maybe Lancer should refuse to do this?

**Comment by glyph** [comment]
This might be like a `FilePath` thing where we should use `fdopen` and `mode` and stuff...

**Comment by twm** [comment]
Yeah I think I have Twisted services at work that make oddly executable files too...

Looks like https://twistedmatrix.com/trac/ticket/9214 is the ticket.

**Comment by glyph** [comment]
@twm A PR would definitely be appreciated :)
